### PR TITLE
Allow installation via non-interactive mode

### PR DESCRIPTION
**Pull request by muschellij2**
Need non-interactive mode for Rvision as it requires opencvlite to be installed

### CODE REVIEW

**Comment by sjmgarnier** [comment]
@muschellij2 I cannot merge this commit as it would create a conflict with CRAN's policy. There used to be a non-interactive installation mode in ROpenCVLite but it prevented the package from being accepted on CRAN because the user has to be able to decide on the installation of a third-party program (OpenCV) on their machine. 

The relevant bit in CRAN's policy:

> "- Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.
> Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user."

**Comment by muschellij2** [comment]
I agree - but the flag is FALSE by default, which aligns with the policy.
The defaults is the same as before, but for CI tests, this allows a flag to
enable this.
Best,
John

**Comment by sjmgarnier** [comment]
@muschellij2 Do you know examples of CRAN packages using this approach? I don't want to do another round of back and forth with the CRAN maintainers to have them tell me to roll this back again.

**Comment by muschellij2** [comment]
I do not.  I don't know the right answer, but the fact that `installOpenCV` behavior is exactly the same default behavior as before would seemingly be fine.  I would say the other option is to put a CI check **inside** the `installOpenCV` function (or check `options`) to do it.

For example:
```r
installOpenCV = function() {
force_install = getOption("install_open_cv", FALSE)
install = ifelse(force_install, 0, 1)
}
``` 
Where someone can set `options(install_open_cv = TRUE)` to have this function to work.

**Comment by muschellij2** [comment]
Any thoughts on this? I've set it up for only to work on the CI systems.

**Comment by muschellij2** [comment]
Not all are not for this package.  They are part of our default
Neuroconductor build on Appveyor, but the Python/Conda stuff can be
disregarded but the

NOT_CRAN: true
R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

are set to 1) be more like CRAN build and 2) allow remotes installations
not break a build simply due to a warning.



Best,
John

**Comment by sjmgarnier** [comment]
@muschellij2 I merged the PR. I will now update the package to work with the latest version of OpenCV and push it to CRAN today if everything works.

**Comment by sjmgarnier** [comment]
@muschellij2 ROpenCVLite 0.3.412 is on CRAN now. Thanks for your help! On to Rvision now!

**Pull request merged**
